import React, { useState } from "react";
import { Bot, Copy, Check, Zap, Clock, Info } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { motion, AnimatePresence } from "framer-motion";
import { SourceReference } from "../lib/api";

interface AnswerCardProps {
  answer: string;
  timeTaken: number;
  modelUsed: string;
  sources?: SourceReference[];
}

export default function AnswerCard({
  answer,
  timeTaken,
  modelUsed,
  sources = [],
}: AnswerCardProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(answer);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy text: ", err);
    }
  };

  // Group sources by filename for dynamic citation generation
  const citations: Record<string, Set<number>> = {};
  sources.forEach((src) => {
    const name = src.source || "Document";
    if (!citations[name]) {
      citations[name] = new Set<number>();
    }
    if (src.page) {
      citations[name].add(src.page);
    }
  });

  return (
    <div className="w-full bg-[#0f172a]/80 border border-slate-800/80 rounded-2xl p-5 shadow-xl backdrop-blur-md">
      {/* Header */}
      <div className="flex items-center gap-2 mb-3">
        <div className="flex items-center justify-center w-7 h-7 rounded-lg bg-purple-500/10 text-purple-400 border border-purple-500/20">
          <Bot className="w-4.5 h-4.5" />
        </div>
        <h4 className="text-xs font-bold text-white uppercase tracking-wider">
          AI Answer
        </h4>
      </div>

      {/* Answer Body Container */}
      <div className="bg-[#0b0d19]/80 border border-slate-900 rounded-xl p-4 min-h-[120px] text-sm leading-relaxed text-slate-200">
        <div className="prose prose-invert max-w-none text-xs font-medium space-y-2.5">
          <ReactMarkdown
            components={{
              p: ({ node, ...props }) => <p className="mb-2 last:mb-0" {...props} />,
              ul: ({ node, ...props }) => <ul className="list-disc pl-5 mb-2 space-y-1" {...props} />,
              ol: ({ node, ...props }) => <ol className="list-decimal pl-5 mb-2 space-y-1" {...props} />,
              li: ({ node, ...props }) => <li className="mb-0.5" {...props} />,
              strong: ({ node, ...props }) => <strong className="font-bold text-white" {...props} />,
              code: ({ node, ...props }) => (
                <code className="bg-slate-950 px-1 py-0.5 rounded text-[11px] font-mono text-purple-400 border border-slate-800" {...props} />
              ),
            }}
          >
            {answer}
          </ReactMarkdown>
        </div>

        {/* Dynamic Citations Box */}
        {Object.keys(citations).length > 0 && (
          <div className="mt-4 border-t border-slate-900/60 pt-3 text-[10px] text-slate-400">
            <span className="font-extrabold text-slate-300 uppercase tracking-widest flex items-center gap-1 mb-1.5">
              <Info className="w-3.5 h-3.5 text-purple-400" /> Grounding Citations
            </span>
            <ul className="list-none pl-0 space-y-1">
              {Object.entries(citations).map(([filename, pages]) => (
                <li key={filename} className="flex items-center gap-1.5 font-semibold">
                  <span className="text-purple-400">●</span>
                  <span>
                    PDF: <span className="text-slate-200">{filename}</span> | Pages:{" "}
                    <span className="text-cyan-400 font-extrabold">
                      {Array.from(pages)
                        .sort((a, b) => a - b)
                        .join(", ")}
                    </span>
                  </span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {/* Footer Controls */}
      <div className="flex items-center justify-between mt-3 text-[10px] text-slate-500">
        <div className="flex items-center gap-4">
          {/* Model Name */}
          <div className="flex items-center gap-1">
            <Zap className="w-3.5 h-3.5 text-amber-400" />
            <span>
              Generated by <span className="font-semibold text-slate-400">{modelUsed}</span>
            </span>
          </div>

          {/* Execution Time */}
          <div className="flex items-center gap-1">
            <Clock className="w-3.5 h-3.5 text-cyan-400" />
            <span>
              Speed: <span className="font-semibold text-slate-400">{timeTaken}s</span>
            </span>
          </div>
        </div>

        {/* Copy Button */}
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 px-2.5 py-1 rounded bg-slate-900/60 border border-slate-800 hover:border-slate-700 hover:text-slate-300 font-semibold transition-all cursor-pointer"
        >
          <AnimatePresence mode="wait">
            {copied ? (
              <motion.span
                key="copied"
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0 }}
                className="flex items-center gap-1 text-emerald-400"
              >
                <Check className="w-3 h-3" />
                <span>Copied</span>
              </motion.span>
            ) : (
              <motion.span
                key="copy"
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0 }}
                className="flex items-center gap-1 text-slate-400 hover:text-slate-300"
              >
                <Copy className="w-3 h-3" />
                <span>Copy</span>
              </motion.span>
            )}
          </AnimatePresence>
        </button>
      </div>
    </div>
  );
}
